"""Sincronizar modelos SQLAlchemy con estructura actual

Revision ID: a93ebf45de70
Revises: cf6695b8bf8f
Create Date: 2025-11-15 19:11:06.286602

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a93ebf45de70'
down_revision: Union[str, Sequence[str], None] = 'cf6695b8bf8f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cotizaciones',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('empresa_nit', sa.String(), nullable=True),
    sa.Column('periodo', sa.String(), nullable=False),
    sa.Column('tipo_cotizacion', sa.String(), nullable=True),
    sa.Column('base_cotizacion', sa.Float(), nullable=True),
    sa.Column('porcentaje', sa.Float(), nullable=True),
    sa.Column('valor_empresa', sa.Float(), nullable=True),
    sa.Column('valor_empleado', sa.Float(), nullable=True),
    sa.Column('total', sa.Float(), nullable=True),
    sa.Column('estado', sa.String(), nullable=True),
    sa.Column('fecha_pago', sa.String(), nullable=True),
    sa.Column('comprobante', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['empresa_nit'], ['empresas.nit'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('incapacidades',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('numero_incapacidad', sa.String(), nullable=True),
    sa.Column('tipo_incapacidad', sa.String(), nullable=True),
    sa.Column('diagnostico', sa.Text(), nullable=True),
    sa.Column('fecha_inicio', sa.String(), nullable=False),
    sa.Column('fecha_fin', sa.String(), nullable=True),
    sa.Column('dias_incapacidad', sa.Integer(), nullable=True),
    sa.Column('ibc_incapacidad', sa.Float(), nullable=True),
    sa.Column('porcentaje_pago', sa.Float(), nullable=True),
    sa.Column('valor_dia', sa.Float(), nullable=True),
    sa.Column('valor_total', sa.Float(), nullable=True),
    sa.Column('paga_empresa', sa.Boolean(), nullable=True),
    sa.Column('paga_eps', sa.Boolean(), nullable=True),
    sa.Column('paga_arl', sa.Boolean(), nullable=True),
    sa.Column('estado', sa.String(), nullable=True),
    sa.Column('documento_soporte', sa.String(), nullable=True),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notificaciones',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('titulo', sa.String(), nullable=False),
    sa.Column('mensaje', sa.Text(), nullable=False),
    sa.Column('tipo', sa.String(), nullable=True),
    sa.Column('categoria', sa.String(), nullable=True),
    sa.Column('leida', sa.Boolean(), nullable=True),
    sa.Column('fecha_lectura', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pagos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('periodo', sa.String(), nullable=False),
    sa.Column('fecha_pago', sa.String(), nullable=True),
    sa.Column('tipo_pago', sa.String(), nullable=True),
    sa.Column('salario_base', sa.Float(), nullable=True),
    sa.Column('aux_transporte', sa.Float(), nullable=True),
    sa.Column('bonificaciones', sa.Float(), nullable=True),
    sa.Column('horas_extras', sa.Float(), nullable=True),
    sa.Column('comisiones', sa.Float(), nullable=True),
    sa.Column('total_devengado', sa.Float(), nullable=True),
    sa.Column('salud', sa.Float(), nullable=True),
    sa.Column('pension', sa.Float(), nullable=True),
    sa.Column('fondo_solidaridad', sa.Float(), nullable=True),
    sa.Column('retencion_fuente', sa.Float(), nullable=True),
    sa.Column('otras_deducciones', sa.Float(), nullable=True),
    sa.Column('total_deducciones', sa.Float(), nullable=True),
    sa.Column('neto_pagar', sa.Float(), nullable=True),
    sa.Column('estado', sa.String(), nullable=True),
    sa.Column('metodo_pago', sa.String(), nullable=True),
    sa.Column('comprobante', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tutelas',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('numero_tutela', sa.String(), nullable=True),
    sa.Column('juzgado', sa.String(), nullable=True),
    sa.Column('fecha_notificacion', sa.String(), nullable=True),
    sa.Column('fecha_inicio', sa.String(), nullable=True),
    sa.Column('fecha_fin', sa.String(), nullable=True),
    sa.Column('valor_total', sa.Float(), nullable=True),
    sa.Column('valor_cuota', sa.Float(), nullable=True),
    sa.Column('numero_cuotas', sa.Integer(), nullable=True),
    sa.Column('cuotas_pagadas', sa.Integer(), nullable=True),
    sa.Column('saldo_pendiente', sa.Float(), nullable=True),
    sa.Column('estado', sa.String(), nullable=True),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('numero_tutela')
    )
    op.drop_index(op.f('idx_audit_registro'), table_name='audit_log')
    op.drop_index(op.f('idx_audit_tabla_fecha'), table_name='audit_log')
    op.drop_table('audit_log')
    op.drop_table('portal_users')
    op.drop_index(op.f('idx_formularios_nombre'), table_name='formularios_importados')
    op.drop_table('formularios_importados')
    op.alter_column('empresas', 'id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
    op.alter_column('empresas', 'nombre_empresa',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('empresas', 'tipo_identificacion_empresa',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('empresas', 'nit',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('empresas', 'direccion_empresa',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('empresas', 'telefono_empresa',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('empresas', 'correo_empresa',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('empresas', 'departamento_empresa',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('empresas', 'ciudad_empresa',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('empresas', 'ibc_empresa',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('empresas', 'afp_empresa',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('empresas', 'arl_empresa',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('empresas', 'rep_legal_nombre',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('empresas', 'rep_legal_tipo_id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('empresas', 'rep_legal_numero_id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('empresas', 'estado',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True,
               existing_server_default=sa.text("'Activo'"))
    op.alter_column('empresas', 'created_at',
               existing_type=sa.TEXT(),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('empresas', 'updated_at',
               existing_type=sa.TEXT(),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.drop_index(op.f('idx_empresas_nombre'), table_name='empresas')
    op.add_column('usuarios', sa.Column('tiempoServicio', sa.String(), nullable=True))
    op.add_column('usuarios', sa.Column('cargo', sa.String(), nullable=True))
    op.add_column('usuarios', sa.Column('salarioMensual', sa.Float(), nullable=True))
    op.add_column('usuarios', sa.Column('aux_transporte', sa.Float(), nullable=True))
    op.add_column('usuarios', sa.Column('bonificacion_mensual', sa.Float(), nullable=True))
    op.add_column('usuarios', sa.Column('aux_alimentacion', sa.Float(), nullable=True))
    op.add_column('usuarios', sa.Column('aux_rodamiento', sa.Float(), nullable=True))
    op.add_column('usuarios', sa.Column('estado_civil', sa.String(), nullable=True))
    op.add_column('usuarios', sa.Column('nivel_estudios', sa.String(), nullable=True))
    op.add_column('usuarios', sa.Column('es_cabeza_familia', sa.String(), nullable=True))
    op.add_column('usuarios', sa.Column('contacto_emergencia_nombre', sa.String(), nullable=True))
    op.add_column('usuarios', sa.Column('contacto_emergencia_telefono', sa.String(), nullable=True))
    op.add_column('usuarios', sa.Column('contacto_emergencia_parentesco', sa.String(), nullable=True))
    op.alter_column('usuarios', 'id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
    op.alter_column('usuarios', 'empresa_nit',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('usuarios', 'tipoId',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('usuarios', 'numeroId',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('usuarios', 'primerNombre',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('usuarios', 'segundoNombre',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('usuarios', 'primerApellido',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('usuarios', 'segundoApellido',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('usuarios', 'sexoBiologico',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('usuarios', 'sexoIdentificacion',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('usuarios', 'nacionalidad',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('usuarios', 'fechaNacimiento',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('usuarios', 'paisNacimiento',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('usuarios', 'departamentoNacimiento',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('usuarios', 'municipioNacimiento',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('usuarios', 'direccion',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('usuarios', 'telefonoCelular',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('usuarios', 'telefonoFijo',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('usuarios', 'correoElectronico',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('usuarios', 'comunaBarrio',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('usuarios', 'afpNombre',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('usuarios', 'afpCosto',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('usuarios', 'epsNombre',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('usuarios', 'epsCosto',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('usuarios', 'arlNombre',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('usuarios', 'arlCosto',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('usuarios', 'ccfNombre',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('usuarios', 'ccfCosto',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('usuarios', 'administracion',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('usuarios', 'ibc',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('usuarios', 'claseRiesgoARL',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('usuarios', 'fechaIngreso',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('usuarios', 'password_hash',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('usuarios', 'role',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True,
               existing_server_default=sa.text("'user'"))
    op.alter_column('usuarios', 'estado',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True,
               existing_server_default=sa.text("'Activo'"))
    op.alter_column('usuarios', 'created_at',
               existing_type=sa.TEXT(),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('usuarios', 'updated_at',
               existing_type=sa.TEXT(),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.drop_index(op.f('idx_usuarios_email'), table_name='usuarios')
    op.drop_index(op.f('idx_usuarios_empresa'), table_name='usuarios')
    op.drop_index(op.f('idx_usuarios_nombre'), table_name='usuarios')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('idx_usuarios_nombre'), 'usuarios', ['primerNombre', 'primerApellido'], unique=False)
    op.create_index(op.f('idx_usuarios_empresa'), 'usuarios', ['empresa_nit'], unique=False)
    op.create_index(op.f('idx_usuarios_email'), 'usuarios', ['correoElectronico'], unique=False)
    op.alter_column('usuarios', 'updated_at',
               existing_type=sa.DateTime(),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('usuarios', 'created_at',
               existing_type=sa.DateTime(),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('usuarios', 'estado',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text("'Activo'"))
    op.alter_column('usuarios', 'role',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text("'user'"))
    op.alter_column('usuarios', 'password_hash',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('usuarios', 'fechaIngreso',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('usuarios', 'claseRiesgoARL',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('usuarios', 'ibc',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)
    op.alter_column('usuarios', 'administracion',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('usuarios', 'ccfCosto',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('usuarios', 'ccfNombre',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('usuarios', 'arlCosto',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('usuarios', 'arlNombre',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('usuarios', 'epsCosto',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('usuarios', 'epsNombre',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('usuarios', 'afpCosto',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('usuarios', 'afpNombre',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('usuarios', 'comunaBarrio',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('usuarios', 'correoElectronico',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('usuarios', 'telefonoFijo',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('usuarios', 'telefonoCelular',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('usuarios', 'direccion',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('usuarios', 'municipioNacimiento',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('usuarios', 'departamentoNacimiento',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('usuarios', 'paisNacimiento',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('usuarios', 'fechaNacimiento',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('usuarios', 'nacionalidad',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('usuarios', 'sexoIdentificacion',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('usuarios', 'sexoBiologico',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('usuarios', 'segundoApellido',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('usuarios', 'primerApellido',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('usuarios', 'segundoNombre',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('usuarios', 'primerNombre',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('usuarios', 'numeroId',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('usuarios', 'tipoId',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('usuarios', 'empresa_nit',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('usuarios', 'id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
    op.drop_column('usuarios', 'contacto_emergencia_parentesco')
    op.drop_column('usuarios', 'contacto_emergencia_telefono')
    op.drop_column('usuarios', 'contacto_emergencia_nombre')
    op.drop_column('usuarios', 'es_cabeza_familia')
    op.drop_column('usuarios', 'nivel_estudios')
    op.drop_column('usuarios', 'estado_civil')
    op.drop_column('usuarios', 'aux_rodamiento')
    op.drop_column('usuarios', 'aux_alimentacion')
    op.drop_column('usuarios', 'bonificacion_mensual')
    op.drop_column('usuarios', 'aux_transporte')
    op.drop_column('usuarios', 'salarioMensual')
    op.drop_column('usuarios', 'cargo')
    op.drop_column('usuarios', 'tiempoServicio')
    op.create_index(op.f('idx_empresas_nombre'), 'empresas', ['nombre_empresa'], unique=False)
    op.alter_column('empresas', 'updated_at',
               existing_type=sa.DateTime(),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('empresas', 'created_at',
               existing_type=sa.DateTime(),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('empresas', 'estado',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text("'Activo'"))
    op.alter_column('empresas', 'rep_legal_numero_id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('empresas', 'rep_legal_tipo_id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('empresas', 'rep_legal_nombre',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('empresas', 'arl_empresa',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('empresas', 'afp_empresa',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('empresas', 'ibc_empresa',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)
    op.alter_column('empresas', 'ciudad_empresa',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('empresas', 'departamento_empresa',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('empresas', 'correo_empresa',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('empresas', 'telefono_empresa',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('empresas', 'direccion_empresa',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('empresas', 'nit',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('empresas', 'tipo_identificacion_empresa',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('empresas', 'nombre_empresa',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('empresas', 'id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
    op.create_table('formularios_importados',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('nombre', sa.TEXT(), nullable=False),
    sa.Column('nombre_archivo', sa.TEXT(), nullable=False),
    sa.Column('ruta_archivo', sa.TEXT(), nullable=False),
    sa.Column('campos_mapeados', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.TEXT(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.TEXT(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre_archivo')
    )
    op.create_index(op.f('idx_formularios_nombre'), 'formularios_importados', ['nombre'], unique=False)
    op.create_table('portal_users',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('nombre', sa.TEXT(), nullable=False),
    sa.Column('email', sa.TEXT(), nullable=False),
    sa.Column('password_hash', sa.TEXT(), nullable=False),
    sa.Column('fecha_creacion', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('ultimo_acceso', sa.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('audit_log',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('tabla', sa.TEXT(), nullable=False),
    sa.Column('registro_id', sa.INTEGER(), nullable=False),
    sa.Column('accion', sa.TEXT(), nullable=False),
    sa.Column('usuario', sa.TEXT(), nullable=True),
    sa.Column('fecha_hora', sa.TEXT(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('datos_anteriores', sa.TEXT(), nullable=True),
    sa.Column('datos_nuevos', sa.TEXT(), nullable=True),
    sa.CheckConstraint("accion IN ('INSERT', 'UPDATE', 'DELETE')"),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('idx_audit_tabla_fecha'), 'audit_log', ['tabla', 'fecha_hora'], unique=False)
    op.create_index(op.f('idx_audit_registro'), 'audit_log', ['tabla', 'registro_id'], unique=False)
    op.drop_table('tutelas')
    op.drop_table('pagos')
    op.drop_table('notificaciones')
    op.drop_table('incapacidades')
    op.drop_table('cotizaciones')
    # ### end Alembic commands ###
